// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package types

type Book struct {
	ID     string `json:"id"`
	Title  string `json:"title"`
	Author *User  `json:"author"`
}

type SearchUserInput struct {
	ID string `json:"id"`
}

type User struct {
	ID    string `json:"id"`
	Name  string `json:"name"`
	Email string `json:"email"`
}
