name: PUSH CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: checkout
      - name: cache docker image
        uses: actions/cache@v2
        with:
          path: |
            ./docker_image.tar
          key: ${{ runner.os }}-${{ GITHUB.SHA }}-docker-image
      - name: build
        run: |
          REPO_NAME="$(echo $GITHUB_REPOSITORY | sed 'y/ABCDEFGHIJKLMNOPQRSTUVWXYZ/abcdefghijklmnopqrstuvwxyz/')"
          docker build . -f ./.dockerfile -t $REPO_NAME &&
          docker save -o ./docker_image.tar $REPO_NAME
